//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FuseConfig) DeepCopyInto(out *FuseConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FuseConfig.
func (in *FuseConfig) DeepCopy() *FuseConfig {
	if in == nil {
		return nil
	}
	out := new(FuseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjcacheCluster) DeepCopyInto(out *ObjcacheCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjcacheCluster.
func (in *ObjcacheCluster) DeepCopy() *ObjcacheCluster {
	if in == nil {
		return nil
	}
	out := new(ObjcacheCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObjcacheCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjcacheClusterList) DeepCopyInto(out *ObjcacheClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ObjcacheCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjcacheClusterList.
func (in *ObjcacheClusterList) DeepCopy() *ObjcacheClusterList {
	if in == nil {
		return nil
	}
	out := new(ObjcacheClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObjcacheClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjcacheClusterSpec) DeepCopyInto(out *ObjcacheClusterSpec) {
	*out = *in
	if in.Shards != nil {
		in, out := &in.Shards, &out.Shards
		*out = new(int)
		**out = **in
	}
	in.ServerConfig.DeepCopyInto(&out.ServerConfig)
	if in.GoDebugEnvVar != nil {
		in, out := &in.GoDebugEnvVar, &out.GoDebugEnvVar
		*out = new(string)
		**out = **in
	}
	if in.GoMemLimit != nil {
		in, out := &in.GoMemLimit, &out.GoMemLimit
		*out = new(string)
		**out = **in
	}
	if in.MultiNicName != nil {
		in, out := &in.MultiNicName, &out.MultiNicName
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = (*in).DeepCopy()
	}
	in.LocalVolume.DeepCopyInto(&out.LocalVolume)
	if in.OverridePodSpec != nil {
		in, out := &in.OverridePodSpec, &out.OverridePodSpec
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjcacheClusterSpec.
func (in *ObjcacheClusterSpec) DeepCopy() *ObjcacheClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ObjcacheClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjcacheClusterStatus) DeepCopyInto(out *ObjcacheClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjcacheClusterStatus.
func (in *ObjcacheClusterStatus) DeepCopy() *ObjcacheClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ObjcacheClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjcacheConfig) DeepCopyInto(out *ObjcacheConfig) {
	*out = *in
	if in.MountOptions != nil {
		in, out := &in.MountOptions, &out.MountOptions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjcacheConfig.
func (in *ObjcacheConfig) DeepCopy() *ObjcacheConfig {
	if in == nil {
		return nil
	}
	out := new(ObjcacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjcacheCsiDriver) DeepCopyInto(out *ObjcacheCsiDriver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjcacheCsiDriver.
func (in *ObjcacheCsiDriver) DeepCopy() *ObjcacheCsiDriver {
	if in == nil {
		return nil
	}
	out := new(ObjcacheCsiDriver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObjcacheCsiDriver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjcacheCsiDriverList) DeepCopyInto(out *ObjcacheCsiDriverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ObjcacheCsiDriver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjcacheCsiDriverList.
func (in *ObjcacheCsiDriverList) DeepCopy() *ObjcacheCsiDriverList {
	if in == nil {
		return nil
	}
	out := new(ObjcacheCsiDriverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObjcacheCsiDriverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjcacheCsiDriverSpec) DeepCopyInto(out *ObjcacheCsiDriverSpec) {
	*out = *in
	out.Images = in.Images
	in.LocalVolume.DeepCopyInto(&out.LocalVolume)
	if in.MultiNicName != nil {
		in, out := &in.MultiNicName, &out.MultiNicName
		*out = new(string)
		**out = **in
	}
	if in.FuseGoDebugEnvVar != nil {
		in, out := &in.FuseGoDebugEnvVar, &out.FuseGoDebugEnvVar
		*out = new(string)
		**out = **in
	}
	if in.FuseGoMemLimit != nil {
		in, out := &in.FuseGoMemLimit, &out.FuseGoMemLimit
		*out = new(string)
		**out = **in
	}
	out.FuseConfig = in.FuseConfig
	if in.OverridePodTemplateSpec != nil {
		in, out := &in.OverridePodTemplateSpec, &out.OverridePodTemplateSpec
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjcacheCsiDriverSpec.
func (in *ObjcacheCsiDriverSpec) DeepCopy() *ObjcacheCsiDriverSpec {
	if in == nil {
		return nil
	}
	out := new(ObjcacheCsiDriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjcacheCsiDriverStatus) DeepCopyInto(out *ObjcacheCsiDriverStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjcacheCsiDriverStatus.
func (in *ObjcacheCsiDriverStatus) DeepCopy() *ObjcacheCsiDriverStatus {
	if in == nil {
		return nil
	}
	out := new(ObjcacheCsiDriverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjcacheImages) DeepCopyInto(out *ObjcacheImages) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjcacheImages.
func (in *ObjcacheImages) DeepCopy() *ObjcacheImages {
	if in == nil {
		return nil
	}
	out := new(ObjcacheImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjcacheLocalVolume) DeepCopyInto(out *ObjcacheLocalVolume) {
	*out = *in
	out.Capacity = in.Capacity.DeepCopy()
	if in.DebugLogPvc != nil {
		in, out := &in.DebugLogPvc, &out.DebugLogPvc
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjcacheLocalVolume.
func (in *ObjcacheLocalVolume) DeepCopy() *ObjcacheLocalVolume {
	if in == nil {
		return nil
	}
	out := new(ObjcacheLocalVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSpecApplyConfiguration) DeepCopyInto(out *PodSpecApplyConfiguration) {
	clone := in.DeepCopy()
	*out = *clone
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodTemplateSpecApplyConfiguration) DeepCopyInto(out *PodTemplateSpecApplyConfiguration) {
	clone := in.DeepCopy()
	*out = *clone
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirementsApplyConfiguration) DeepCopyInto(out *ResourceRequirementsApplyConfiguration) {
	clone := in.DeepCopy()
	*out = *clone
}
