# permissions for end users to view objcachecsidrivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: objcachecsidriver-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: objcache-operator
    app.kubernetes.io/part-of: objcache-operator
    app.kubernetes.io/managed-by: kustomize
  name: objcachecsidriver-viewer-role
rules:
- apiGroups:
  - trl.ibm.com
  resources:
  - objcachecsidrivers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - trl.ibm.com
  resources:
  - objcachecsidrivers/status
  verbs:
  - get
