apiVersion: trl.ibm.com/v1alpha1
kind: ObjcacheCluster
metadata:
  name: objcache-sample
spec:
  generatedStorageClassName: objcache-sample
  shards: 3
  raftFollowers: 0
  seed: 202305101353
  secret: objcache-secret
  overridePodSpec:
    imagePullSecrets:
    - name: taas
  serverConfig: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: objcache-sample-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: objcache-sample
